### ISSUE TITLE
Obtain weekly brush statistics

### ISSUE THREAD

**Issue by aGhandhii** [dummmylitt/Group6Mirror#1]
group existing brush data into averages by week, and compare current week to previous ones?

Store in a separate JSON file, maybe `toothbrush_weekly.json`?

Example:
```json
{
    "week of 4-16-2024" {
        "average time": 10,
        "average brush count": 2
    },
    "week of 4-9-2024" {
        "average time": 3,
        "average brush count": 1
    }
}
```

**Comment by changauds** [comment]
Why do we want to compare each week w/ each other? Additional funcitnoality?

**Comment by aGhandhii** [comment]
it would be cool to display a historical average as well as a weekly average, Im kinda just making this issue so we have options for additional functionality
